// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBmYcBEEnoPe6ynzFL8lpNtHBCRQYJH1M',
    appId: '1:642806796317:web:3e14ae9b6caf0721a1b6f4',
    messagingSenderId: '642806796317',
    projectId: 'smarthouse-52ff0',
    authDomain: 'smarthouse-52ff0.firebaseapp.com',
    databaseURL: 'https://smarthouse-52ff0-default-rtdb.firebaseio.com',
    storageBucket: 'smarthouse-52ff0.appspot.com',
    measurementId: 'G-J51149M746',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCePpX0laboiVscU24ykH2iwGSOHFsjDd4',
    appId: '1:642806796317:android:c057d233ace84f64a1b6f4',
    messagingSenderId: '642806796317',
    projectId: 'smarthouse-52ff0',
    databaseURL: 'https://smarthouse-52ff0-default-rtdb.firebaseio.com',
    storageBucket: 'smarthouse-52ff0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC65NXPuPC02vXoLd05jpAqKCjARVcpd_4',
    appId: '1:642806796317:ios:349e965e459fb543a1b6f4',
    messagingSenderId: '642806796317',
    projectId: 'smarthouse-52ff0',
    databaseURL: 'https://smarthouse-52ff0-default-rtdb.firebaseio.com',
    storageBucket: 'smarthouse-52ff0.appspot.com',
    iosBundleId: 'com.example.smarthouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC65NXPuPC02vXoLd05jpAqKCjARVcpd_4',
    appId: '1:642806796317:ios:349e965e459fb543a1b6f4',
    messagingSenderId: '642806796317',
    projectId: 'smarthouse-52ff0',
    databaseURL: 'https://smarthouse-52ff0-default-rtdb.firebaseio.com',
    storageBucket: 'smarthouse-52ff0.appspot.com',
    iosBundleId: 'com.example.smarthouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBmYcBEEnoPe6ynzFL8lpNtHBCRQYJH1M',
    appId: '1:642806796317:web:d447db1784ffec67a1b6f4',
    messagingSenderId: '642806796317',
    projectId: 'smarthouse-52ff0',
    authDomain: 'smarthouse-52ff0.firebaseapp.com',
    databaseURL: 'https://smarthouse-52ff0-default-rtdb.firebaseio.com',
    storageBucket: 'smarthouse-52ff0.appspot.com',
    measurementId: 'G-Z3N0SHW4LJ',
  );
}
